/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DMarcas;
import Datos.DModelos;
import Datos.DServicios;
import Metodos.Metodos;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author AlejandroSaenz
 */
public class AñadirServicios extends javax.swing.JFrame {

    public TextAutoCompleter ac;
    Metodos Met = new Metodos();

    public AñadirServicios() {
        initComponents();
                setResizable(false);

        TMarca.setVisible(false);
        TModelo.setVisible(false);
        TServicio.setVisible(false);
        TPrecio.setVisible(false);
        ac = Met.autocompletarMarca(txtMarca);

        setLocationRelativeTo(null);
        LlenarComboMarca();
        Met.MostrarTablaServicios(TablaServicios, ComboMarca4.getSelectedItem().toString(), ComboModelo1.getSelectedItem().toString());
    }

    public void LlenarComboMarca() {

        Metodos me = new Metodos();
        ComboMarca.setModel(me.LlenarComboMarca());
        ComboMarca2.setModel(me.LlenarComboMarca());
        ComboMarca3.setModel(me.LlenarComboMarca());
        ComboMarca4.setModel(me.LlenarComboMarca());
        ComboModelo.setModel(me.LlenarComboModelo(ComboMarca3.getSelectedItem().toString()));
        ComboModelo1.setModel(me.LlenarComboModelo(ComboMarca3.getSelectedItem().toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Smart = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Servicios = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Productos = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Contraseña = new javax.swing.JLabel();
        CentroCarga = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        ComboMarca = new javax.swing.JComboBox<>();
        ComboMarca2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        ComboModelo = new javax.swing.JComboBox<>();
        ComboMarca3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ComboMarca4 = new javax.swing.JComboBox<>();
        ComboModelo1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaServicios = new javax.swing.JTable();
        TMarca = new javax.swing.JLabel();
        TModelo = new javax.swing.JLabel();
        TServicio = new javax.swing.JLabel();
        TPrecio = new javax.swing.JLabel();
        Boton = new javax.swing.JLabel();
        Boton1 = new javax.swing.JLabel();
        Boton2 = new javax.swing.JLabel();
        Boton3 = new javax.swing.JLabel();
        Boton4 = new javax.swing.JLabel();
        Boton5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1360, 705));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(350, 705));

        Smart.setBackground(new java.awt.Color(204, 204, 0));
        Smart.setFont(new java.awt.Font("Arial Black", 0, 60)); // NOI18N
        Smart.setForeground(new java.awt.Color(255, 255, 255));
        Smart.setText(" SmartCell");
        Smart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Smart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SmartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SmartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SmartMouseExited(evt);
            }
        });

        Servicios.setBackground(new java.awt.Color(204, 204, 204));
        Servicios.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Servicios.setText("        Servicios");
        Servicios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Servicios.setOpaque(true);
        Servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServiciosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ServiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ServiciosMouseExited(evt);
            }
        });

        Productos.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Productos.setForeground(new java.awt.Color(255, 255, 255));
        Productos.setText("       Productos");
        Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductosMouseExited(evt);
            }
        });

        Contraseña.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("      Contraseña");
        Contraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContraseñaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContraseñaMouseExited(evt);
            }
        });

        CentroCarga.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        CentroCarga.setForeground(new java.awt.Color(255, 255, 255));
        CentroCarga.setText("  Centro de carga");
        CentroCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CentroCarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CentroCargaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CentroCargaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CentroCargaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Smart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator4)
                    .addComponent(Servicios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CentroCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(Smart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(Servicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Productos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña)
                .addGap(14, 14, 14)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CentroCarga)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel13.setText("Marca");

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel14.setText("Modelo");

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator20.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Marca:");

        ComboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboMarca2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboMarca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMarca2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca:");

        jLabel3.setText("Modelo:");

        ComboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboModeloActionPerformed(evt);
            }
        });

        ComboMarca3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboMarca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMarca3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel15.setText("Servicio");

        ComboMarca4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboMarca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMarca4ActionPerformed(evt);
            }
        });

        ComboModelo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboModelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboModelo1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Servicio:");

        jLabel5.setText("Precio:");

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        TablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaServicios);

        TMarca.setText("jLabel6");

        TModelo.setText("jLabel6");

        TServicio.setText("jLabel6");

        TPrecio.setText("jLabel6");

        Boton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Boton.setText("    Agregar");
        Boton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        Boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMouseExited(evt);
            }
        });

        Boton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Boton1.setText("    Agregar");
        Boton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton1MouseExited(evt);
            }
        });

        Boton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Boton2.setText("    Agregar");
        Boton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        Boton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton2MouseExited(evt);
            }
        });

        Boton3.setBackground(new java.awt.Color(255, 255, 255));
        Boton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Boton3.setText("     Eliminar");
        Boton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        Boton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton3.setOpaque(true);
        Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton3MouseExited(evt);
            }
        });

        Boton4.setBackground(new java.awt.Color(255, 255, 255));
        Boton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Boton4.setText("     Eliminar");
        Boton4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        Boton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton4.setOpaque(true);
        Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton4MouseExited(evt);
            }
        });

        Boton5.setBackground(new java.awt.Color(255, 255, 255));
        Boton5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Boton5.setText("     Eliminar");
        Boton5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        Boton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton5.setOpaque(true);
        Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(395, 395, 395))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator18)
                                    .addComponent(jSeparator20)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(58, 58, 58)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ComboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ComboMarca3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(67, 67, 67)
                                                .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39))
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(ComboMarca2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel14)
                                                .addGap(395, 395, 395)))))
                                .addContainerGap())
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel1)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(0, 99, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(269, 269, 269)))
                                .addGap(60, 60, 60)
                                .addComponent(ComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(ComboModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5))
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(ComboMarca4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(284, 284, 284)
                                                .addComponent(jLabel4)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(TMarca)
                                        .addGap(189, 189, 189)
                                        .addComponent(TModelo)
                                        .addGap(197, 197, 197)
                                        .addComponent(TServicio)
                                        .addGap(200, 200, 200)
                                        .addComponent(TPrecio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))
                                .addContainerGap())))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(ComboMarca3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboMarca2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboMarca4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TMarca)
                    .addComponent(TModelo)
                    .addComponent(TServicio)
                    .addComponent(TPrecio)
                    .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboMarca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMarca2ActionPerformed
        TextAutoCompleter ac2;
        ac2 = Met.autocompletarModelo(ComboMarca2.getSelectedItem().toString(), txtModelo);
    }//GEN-LAST:event_ComboMarca2ActionPerformed

    private void ComboMarca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMarca3ActionPerformed
        Metodos me = new Metodos();
        ComboModelo.setModel(me.LlenarComboModelo(ComboMarca3.getSelectedItem().toString()));
    }//GEN-LAST:event_ComboMarca3ActionPerformed

    private void ComboMarca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMarca4ActionPerformed

        Metodos me = new Metodos();
        me.MostrarTablaMarcas(TablaServicios,ComboMarca4.getSelectedItem().toString());
        ComboModelo1.setModel(me.LlenarComboModelo(ComboMarca4.getSelectedItem().toString()));        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMarca4ActionPerformed

    private void ComboModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboModeloActionPerformed

    private void ComboModelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboModelo1ActionPerformed
        Met.MostrarTablaServicios(TablaServicios, ComboMarca4.getSelectedItem().toString(), ComboModelo1.getSelectedItem().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_ComboModelo1ActionPerformed

    private void TablaServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaServiciosMouseClicked
        TMarca.setVisible(true);
        TModelo.setVisible(true);
        TServicio.setVisible(true);
        TPrecio.setVisible(true);
        if (evt.getButton() == 1) {
            int fila = TablaServicios.getSelectedRow();
            TMarca.setText(TablaServicios.getValueAt(fila, 0).toString());
            TModelo.setText(TablaServicios.getValueAt(fila, 1).toString());
            TServicio.setText(TablaServicios.getValueAt(fila, 2).toString());
            TPrecio.setText(TablaServicios.getValueAt(fila, 3).toString());

        }
    }//GEN-LAST:event_TablaServiciosMouseClicked

    private void SmartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmartMouseClicked

        dispose();
    }//GEN-LAST:event_SmartMouseClicked

    private void SmartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmartMouseEntered
        Smart.setOpaque(true);
        Smart.setBackground(Color.LIGHT_GRAY);
        Smart.setFont(new java.awt.Font("Arial Black", 0, 62));
    }//GEN-LAST:event_SmartMouseEntered

    private void SmartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmartMouseExited
        Smart.setOpaque(false);
        Smart.setBackground(Color.white);
        Smart.setFont(new java.awt.Font("Arial Black", 0, 60));
        Smart.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_SmartMouseExited

    private void ServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiciosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosMouseClicked

    private void ServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiciosMouseEntered


    }//GEN-LAST:event_ServiciosMouseEntered

    private void ServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosMouseExited

    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
        AñadirProductos P = new AñadirProductos();
        P.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProductosMouseClicked

    private void ProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseEntered
        Productos.setOpaque(true);
        Productos.setBackground(Color.LIGHT_GRAY);
        Productos.setFont(new java.awt.Font("Arial Black", 0, 38));        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosMouseEntered

    private void ProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseExited
        Productos.setOpaque(false);
        Productos.setBackground(Color.white);
        Productos.setFont(new java.awt.Font("Arial Black", 0, 36));        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosMouseExited

    private void ContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñaMouseClicked
        ModificarContraseña A = new ModificarContraseña();
        A.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaMouseClicked

    private void ContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñaMouseEntered
        Contraseña.setOpaque(true);
        Contraseña.setBackground(Color.LIGHT_GRAY);
        Contraseña.setFont(new java.awt.Font("Arial Black", 0, 38));         // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaMouseEntered

    private void ContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñaMouseExited
        Contraseña.setOpaque(false);
        Contraseña.setBackground(Color.white);
        Contraseña.setFont(new java.awt.Font("Arial Black", 0, 36));        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaMouseExited

    private void CentroCargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentroCargaMouseClicked
        CentroCarga C = new CentroCarga();
        C.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CentroCargaMouseClicked

    private void CentroCargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentroCargaMouseEntered
        CentroCarga.setOpaque(true);
        CentroCarga.setBackground(Color.LIGHT_GRAY);
        CentroCarga.setFont(new java.awt.Font("Arial Black", 0, 38));           // TODO add your handling code here:
    }//GEN-LAST:event_CentroCargaMouseEntered

    private void CentroCargaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentroCargaMouseExited
        CentroCarga.setOpaque(false);
        CentroCarga.setBackground(Color.white);
        CentroCarga.setFont(new java.awt.Font("Arial Black", 0, 36));        // TODO add your handling code here:
    }//GEN-LAST:event_CentroCargaMouseExited

    private void BotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseClicked
        if ((ComboMarca2.getSelectedItem().toString().equals("Marca")) || (txtModelo.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Por favor elija una marca y escriba un modelo");
        } else {
            String BusquedaModelo = Metodos.Buscar_Modelo(ComboMarca2.getSelectedItem().toString(), txtModelo.getText());
            if (BusquedaModelo.equals("Datos encontrados")) {
                JOptionPane.showMessageDialog(null, "Modelo ya existe");
                txtModelo.setText("");
            } else {
                DModelos Modelo = new DModelos();
                Modelo.setMarca(ComboMarca2.getSelectedItem().toString());
                Modelo.setModelo(txtModelo.getText());
                Met.GuardarModelo(Modelo);
                txtModelo.setText("");
                LlenarComboMarca();
            }
        }
    }//GEN-LAST:event_BotonMouseClicked

    private void BotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseEntered
        Boton.setBackground(Color.black);
        Boton.setOpaque(true);
        Boton.setForeground(Color.white);
        Boton.setFont(new java.awt.Font("Tahoma Bold", 0, 15));        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMouseEntered

    private void BotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseExited
        Boton.setBackground(Color.white);
        Boton.setOpaque(false);
        Boton.setForeground(Color.black);
        Boton.setFont(new java.awt.Font("Tahoma", 0, 15));          // TODO add your handling code here:
    }//GEN-LAST:event_BotonMouseExited

    private void Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseClicked
if(ComboMarca4.getSelectedItem().toString().equals("Marca")||ComboModelo1.getSelectedItem().toString().equals("Modelo")){JOptionPane.showMessageDialog(null, "Por favor elija marca y modelo");}
else {if(txtServicio.getText().isEmpty()||txtPrecio.getText().isEmpty()){JOptionPane.showMessageDialog(null, "Por favor defina servicio y precio");}
else{
        DServicios Servicio = new DServicios();
        Servicio.setMarca(ComboMarca4.getSelectedItem().toString());
        Servicio.setModelo(ComboModelo1.getSelectedItem().toString());
        Servicio.setServicio(txtServicio.getText());
        Servicio.setPrecio(Float.parseFloat(txtPrecio.getText()));
        Metodos Met = new Metodos();
        Met.GuardarServicio(Servicio);
        txtPrecio.setText("");
        txtServicio.setText("");
        Met.MostrarTablaServicios(TablaServicios, ComboMarca4.getSelectedItem().toString(), ComboModelo1.getSelectedItem().toString());}  }      // TODO add your handling code here:
    }//GEN-LAST:event_Boton1MouseClicked

    private void Boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseEntered
        Boton1.setBackground(Color.black);
        Boton1.setOpaque(true);
        Boton1.setForeground(Color.white);
        Boton1.setFont(new java.awt.Font("Tahoma Bold", 0, 15));          // TODO add your handling code here:
    }//GEN-LAST:event_Boton1MouseEntered

    private void Boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseExited
        Boton1.setBackground(Color.white);
        Boton1.setOpaque(false);
        Boton1.setForeground(Color.black);
        Boton1.setFont(new java.awt.Font("Tahoma", 0, 15));        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1MouseExited

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        if (txtMarca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor escriba una marca");
        } else {
            Metodos Me = new Metodos();
            String Mar = Me.Buscar_Marca(txtMarca.getText());
            if (Mar.equals("Marca ya existe")) {
                JOptionPane.showMessageDialog(null, "La marca ya existe");
                txtMarca.setText("");
            } else {
                DMarcas M = new DMarcas();
                M.setMarca(txtMarca.getText());

                Me.GuardarMarca(M);
                txtMarca.setText("");
                LlenarComboMarca();
                ac = Met.autocompletarMarca(txtMarca);
            }
        }
    }//GEN-LAST:event_Boton2MouseClicked

    private void Boton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseEntered
        Boton2.setBackground(Color.black);
        Boton2.setOpaque(true);
        Boton2.setForeground(Color.white);
        Boton2.setFont(new java.awt.Font("Tahoma Bold", 0, 15));          // TODO add your handling code here:
    }//GEN-LAST:event_Boton2MouseEntered

    private void Boton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseExited
        Boton2.setBackground(Color.white);
        Boton2.setOpaque(false);
        Boton2.setForeground(Color.black);
        Boton2.setFont(new java.awt.Font("Tahoma", 0, 15));        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2MouseExited

    private void Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseClicked
        Metodos Met = new Metodos();
        Met.EliminarModelo(ComboMarca3.getSelectedItem().toString(), ComboModelo.getSelectedItem().toString());
        ComboModelo.setModel(Met.LlenarComboModelo(ComboMarca3.getSelectedItem().toString()));

    }//GEN-LAST:event_Boton3MouseClicked

    private void Boton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseEntered
        Boton3.setBackground(Color.black);
        Boton3.setOpaque(true);
        Boton3.setForeground(Color.white);
        Boton3.setFont(new java.awt.Font("Tahoma Bold", 0, 15));         // TODO add your handling code here:
    }//GEN-LAST:event_Boton3MouseEntered

    private void Boton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseExited
        Boton3.setBackground(Color.white);
        Boton3.setForeground(Color.black);
        Boton3.setFont(new java.awt.Font("Tahoma", 0, 15));         // TODO add your handling code here:
    }//GEN-LAST:event_Boton3MouseExited

    private void Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseClicked

        Metodos Met = new Metodos();
        Met.EliminarServicio(TMarca.getText(), TModelo.getText(), TServicio.getText(), Float.parseFloat(TPrecio.getText()));
        Met.MostrarTablaServicios(TablaServicios, ComboMarca4.getSelectedItem().toString(), ComboModelo1.getSelectedItem().toString());        // TODO add your handling code here:
        TMarca.setVisible(false);
        TModelo.setVisible(false);
        TServicio.setVisible(false);
        TPrecio.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton4MouseClicked

    private void Boton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseEntered
        Boton4.setBackground(Color.black);
        Boton4.setOpaque(true);
        Boton4.setForeground(Color.white);
        Boton4.setFont(new java.awt.Font("Tahoma Bold", 0, 15));        // TODO add your handling code here:
    }//GEN-LAST:event_Boton4MouseEntered

    private void Boton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseExited
        Boton4.setBackground(Color.white);
        Boton4.setForeground(Color.black);
        Boton4.setFont(new java.awt.Font("Tahoma", 0, 15));          // TODO add your handling code here:
    }//GEN-LAST:event_Boton4MouseExited

    private void Boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseClicked
        if (ComboMarca.getSelectedItem().toString().equals("Marca")) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una marca");
        } else {
            Metodos Met = new Metodos();
            Met.EliminarMarca(ComboMarca.getSelectedItem().toString());
            LlenarComboMarca();
            ac = Met.autocompletarMarca(txtMarca);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Boton5MouseClicked

    private void Boton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseEntered
        Boton5.setBackground(Color.black);
        Boton5.setOpaque(true);
        Boton5.setForeground(Color.white);
        Boton5.setFont(new java.awt.Font("Tahoma Bold", 0, 15));        // TODO add your handling code here:
    }//GEN-LAST:event_Boton5MouseEntered

    private void Boton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseExited
        Boton5.setBackground(Color.white);
        Boton5.setForeground(Color.black);
        Boton5.setFont(new java.awt.Font("Tahoma", 0, 15));          // TODO add your handling code here:
    }//GEN-LAST:event_Boton5MouseExited

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char car = evt.getKeyChar();
        if (car != '.' && car != '0' && car != '1' && car != '2' && car != '3' && car != '4' && car != '5' && car != '6' && car != '7' && car != '8' && car != '9') {
            evt.consume(); }         // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boton;
    private javax.swing.JLabel Boton1;
    private javax.swing.JLabel Boton2;
    private javax.swing.JLabel Boton3;
    private javax.swing.JLabel Boton4;
    private javax.swing.JLabel Boton5;
    private javax.swing.JLabel CentroCarga;
    private javax.swing.JComboBox<String> ComboMarca;
    private javax.swing.JComboBox<String> ComboMarca2;
    private javax.swing.JComboBox<String> ComboMarca3;
    private javax.swing.JComboBox<String> ComboMarca4;
    private javax.swing.JComboBox<String> ComboModelo;
    private javax.swing.JComboBox<String> ComboModelo1;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Productos;
    private javax.swing.JLabel Servicios;
    private javax.swing.JLabel Smart;
    private javax.swing.JLabel TMarca;
    private javax.swing.JLabel TModelo;
    private javax.swing.JLabel TPrecio;
    private javax.swing.JLabel TServicio;
    private javax.swing.JTable TablaServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
