/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Metodos.Metodos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author AlejandroSaenz
 */
public class ModificarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form ModificarContraseña
     */
    public ModificarContraseña() {
        initComponents();
                setResizable(false);

        setLocationRelativeTo(null);
    }
    public void Procesar(){
     Metodos M=new Metodos();
        String BusquedaContra = M.VerificarContraseñaActual(this.Actual.getText());
        if(BusquedaContra.equals("Contraseña encontrada")){
            if(Nueva.getText().isEmpty()||Nueva2.getText().isEmpty()){JOptionPane.showMessageDialog(null, "Ingrese nueva contraseña");}
            else{
                if(Nueva.getText().equals(Nueva2.getText())){

                    M.ModificarContraseña(Nueva.getText());
                    Actual.setText("");
                    Nueva.setText("");
                    Nueva2.setText("");

                }
                else{JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");}

            }

        }
        else{JOptionPane.showMessageDialog(null, "La contraseña Actual no coincide");}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Smart = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Servicios = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Productos = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Contraseña = new javax.swing.JLabel();
        CentroCarga = new javax.swing.JLabel();
        lbImagenCodigo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Actual = new javax.swing.JPasswordField();
        Nueva = new javax.swing.JPasswordField();
        Nueva2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ace = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 705));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 705));

        Smart.setBackground(new java.awt.Color(204, 204, 0));
        Smart.setFont(new java.awt.Font("Arial Black", 0, 60)); // NOI18N
        Smart.setForeground(new java.awt.Color(255, 255, 255));
        Smart.setText(" SmartCell");
        Smart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Smart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SmartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SmartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SmartMouseExited(evt);
            }
        });

        Servicios.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Servicios.setText("        Servicios");
        Servicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServiciosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ServiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ServiciosMouseExited(evt);
            }
        });

        Productos.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Productos.setForeground(new java.awt.Color(255, 255, 255));
        Productos.setText("       Productos");
        Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductosMouseExited(evt);
            }
        });

        Contraseña.setBackground(new java.awt.Color(204, 204, 204));
        Contraseña.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("      Contraseña");
        Contraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Contraseña.setOpaque(true);
        Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContraseñaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContraseñaMouseExited(evt);
            }
        });

        CentroCarga.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        CentroCarga.setForeground(new java.awt.Color(255, 255, 255));
        CentroCarga.setText("  Centro de carga");
        CentroCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CentroCarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CentroCargaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CentroCargaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CentroCargaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Smart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator4)
                    .addComponent(Servicios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CentroCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Smart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(Servicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Productos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña)
                .addGap(14, 14, 14)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CentroCarga)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        lbImagenCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lbImagenCodigo.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        Actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualActionPerformed(evt);
            }
        });

        Nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaActionPerformed(evt);
            }
        });

        Nueva2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nueva2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña Actual");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva Contraseña");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirmar Contraseña");

        Ace.setFont(new java.awt.Font("Tahoma", 1, 31)); // NOI18N
        Ace.setText("                                               Aceptar");
        Ace.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));
        Ace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(Actual, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nueva2, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                                    .addComponent(Nueva))))
                        .addGap(25, 25, 25))
                    .addComponent(jSeparator6)
                    .addComponent(Ace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nueva2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Ace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImagenCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbImagenCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceMouseClicked
       Procesar();
    }//GEN-LAST:event_AceMouseClicked

    private void AceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceMouseEntered
        Ace.setOpaque(true);
        Ace.setBackground(Color.white);
        Ace.setFont(new java.awt.Font("Tahoma", 1, 35));
        Ace.setText("                                          Aceptar");
    }//GEN-LAST:event_AceMouseEntered

    private void AceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceMouseExited
        Ace.setOpaque(false);
        Ace.setBackground(Color.white);
        Ace.setFont(new java.awt.Font("Tahoma", 1, 31)); 
        Ace.setText("                                               Aceptar");// TODO add your handling code here:
    }//GEN-LAST:event_AceMouseExited

    private void SmartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmartMouseClicked
        
        dispose();
    }//GEN-LAST:event_SmartMouseClicked

    private void SmartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmartMouseEntered
        Smart.setOpaque(true);
        Smart.setBackground(Color.LIGHT_GRAY);
        Smart.setFont(new java.awt.Font("Arial Black", 0, 62));
    }//GEN-LAST:event_SmartMouseEntered

    private void SmartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmartMouseExited
        Smart.setOpaque(false);
        Smart.setBackground(Color.white);
        Smart.setFont(new java.awt.Font("Arial Black", 0, 60));
        Smart.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_SmartMouseExited

    private void ServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiciosMouseClicked
        AñadirServicios A=new AñadirServicios();
        A.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ServiciosMouseClicked

    private void ServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiciosMouseEntered

        Servicios.setOpaque(true);
        Servicios.setBackground(Color.LIGHT_GRAY);
        Servicios.setFont(new java.awt.Font("Arial Black", 0, 38));
    }//GEN-LAST:event_ServiciosMouseEntered

    private void ServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiciosMouseExited
        Servicios.setOpaque(false);
        Servicios.setBackground(Color.white);
        Servicios.setFont(new java.awt.Font("Arial Black", 0, 36));        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosMouseExited

    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
AñadirProductos P=new AñadirProductos();
P.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosMouseClicked

    private void ProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseEntered
        Productos.setOpaque(true);
        Productos.setBackground(Color.LIGHT_GRAY);
        Productos.setFont(new java.awt.Font("Arial Black", 0, 38));        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosMouseEntered

    private void ProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseExited
        Productos.setOpaque(false);
        Productos.setBackground(Color.white);
        Productos.setFont(new java.awt.Font("Arial Black", 0, 36));        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosMouseExited

    private void ContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñaMouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaMouseClicked

    private void ContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñaMouseEntered
          // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaMouseEntered

    private void ContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñaMouseExited
           // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaMouseExited

    private void CentroCargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentroCargaMouseClicked
        CentroCarga C=new CentroCarga();
        C.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CentroCargaMouseClicked

    private void CentroCargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentroCargaMouseEntered
           CentroCarga.setOpaque(true);
        CentroCarga.setBackground(Color.LIGHT_GRAY);
        CentroCarga.setFont(new java.awt.Font("Arial Black", 0, 38));  
    }//GEN-LAST:event_CentroCargaMouseEntered

    private void CentroCargaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentroCargaMouseExited
            CentroCarga.setOpaque(false);
        CentroCarga.setBackground(Color.white);
        CentroCarga.setFont(new java.awt.Font("Arial Black", 0, 36));  
    }//GEN-LAST:event_CentroCargaMouseExited

    private void ActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualActionPerformed
      Nueva.requestFocus();
    }//GEN-LAST:event_ActualActionPerformed

    private void NuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaActionPerformed
Nueva2.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaActionPerformed

    private void Nueva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nueva2ActionPerformed
Procesar();        // TODO add your handling code here:
    }//GEN-LAST:event_Nueva2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ace;
    private javax.swing.JPasswordField Actual;
    private javax.swing.JLabel CentroCarga;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JPasswordField Nueva;
    private javax.swing.JPasswordField Nueva2;
    private javax.swing.JLabel Productos;
    private javax.swing.JLabel Servicios;
    private javax.swing.JLabel Smart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbImagenCodigo;
    // End of variables declaration//GEN-END:variables
}
