/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author AlejandroSaenz
 */
public class Plantilla extends javax.swing.JPanel implements Printable{

    /**
     * Creates new form Plantilla
     */
    public Plantilla() {
        initComponents();
       //  txtId.setText("" + ConsultarInvoice());
        txtN.setVisible(false);
        txtT.setVisible(false);
        txtM.setVisible(false);
        txtMo.setVisible(false);
        JLFecha.setText(Fecha());
    }

public String Fecha() {
        Date Fecha = new Date() {
        };
        SimpleDateFormat FormatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return FormatoFecha.format(Fecha);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        txtEncendido = new javax.swing.JCheckBox();
        txtApagado = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        D = new javax.swing.JTextField();
        C = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        NS = new javax.swing.JLabel();
        JLFecha = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        txtCelular = new javax.swing.JCheckBox();
        txtTablet = new javax.swing.JCheckBox();
        txtComputadora = new javax.swing.JCheckBox();
        G = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        escribir = new javax.swing.JTextField();
        escribir2 = new javax.swing.JTextField();
        txtN = new javax.swing.JLabel();
        txtT = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        escribir4 = new javax.swing.JTextField();
        escribir3 = new javax.swing.JTextField();
        txtMo = new javax.swing.JLabel();
        txtM = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        A1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REal.jpeg"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 16, 361, 115));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 51, 51));
        txtId.setText("00001");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 152, 70, -1));

        txtEncendido.setBackground(new java.awt.Color(255, 255, 255));
        txtEncendido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEncendido.setText("Encendido");
        txtEncendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEncendidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEncendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        txtApagado.setBackground(new java.awt.Color(255, 255, 255));
        txtApagado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtApagado.setText("Apagado");
        txtApagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApagadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Marca:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        Modelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Modelo.setText("Modelo:");
        jPanel1.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        H.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        H.setText("Falla:");
        jPanel1.add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 290, 58));

        C.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        C.setText("Costo:");
        jPanel1.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        A.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        A.setText("Anticipo:");
        jPanel1.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        F.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        F.setText("Nota:");
        jPanel1.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        NS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NS.setText("Numero de servicio");
        jPanel1.add(NS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        JLFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLFecha.setText("Fecha");
        jPanel1.add(JLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre.setText("Nombre:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        Telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Telefono.setText("Telefono:");
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtCelular.setBackground(new java.awt.Color(255, 255, 255));
        txtCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCelular.setText("Celular");
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 257, -1, -1));

        txtTablet.setBackground(new java.awt.Color(255, 255, 255));
        txtTablet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTablet.setText("Tablet");
        txtTablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTabletActionPerformed(evt);
            }
        });
        jPanel1.add(txtTablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 257, -1, -1));

        txtComputadora.setBackground(new java.awt.Color(255, 255, 255));
        txtComputadora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtComputadora.setText("Computadora");
        txtComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComputadoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 257, -1, -1));

        G.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 290, 39));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 208, 349, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 248, 349, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 316, 349, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 349, 349, -1));

        escribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribirActionPerformed(evt);
            }
        });
        jPanel1.add(escribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 182, 232, -1));

        escribir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribir2ActionPerformed(evt);
            }
        });
        jPanel1.add(escribir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 222, 230, -1));

        txtN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtN.setText("a");
        txtN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNMouseClicked(evt);
            }
        });
        jPanel1.add(txtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtT.setText("b");
        txtT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTMouseClicked(evt);
            }
        });
        jPanel1.add(txtT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        Fecha1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Fecha1.setText("Fecha");
        jPanel1.add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        escribir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribir4ActionPerformed(evt);
            }
        });
        jPanel1.add(escribir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 230, -1));

        escribir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribir3ActionPerformed(evt);
            }
        });
        jPanel1.add(escribir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 230, -1));

        txtMo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMo.setText("c");
        txtMo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMoMouseClicked(evt);
            }
        });
        jPanel1.add(txtMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        txtM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM.setText("d");
        txtM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMMouseClicked(evt);
            }
        });
        jPanel1.add(txtM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 60, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 60, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 60, -1));

        A1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        A1.setText("Total:");
        jPanel1.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 340, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel1.setText("con humedad, lineas en pantalla y golpes en el dispositivo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 330, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setText("Autorizo que SmartCell realice la reparacion pertinente en el dispositivo, conociendo el riesgo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 330, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setText("que este lleva sin hacer responsable a SmartCell en caso de cualquier daño");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 330, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel5.setText("*Garantia unicamente por defectos de fabrica, no aplica casos de pantalla estrellada, dispositivos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 350, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 392, 582));
    }// </editor-fold>//GEN-END:initComponents

    private void escribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribirActionPerformed
        txtN.setText(escribir.getText());
        escribir.setVisible(false);
        txtN.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_escribirActionPerformed

    private void escribir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribir2ActionPerformed
        txtT.setVisible(true);
        txtT.setText(escribir2.getText());
        escribir2.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_escribir2ActionPerformed

    private void txtNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNMouseClicked
        escribir.setVisible(true);
        txtN.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNMouseClicked

    private void txtTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTMouseClicked
        escribir2.setVisible(true);
        txtT.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtTMouseClicked

    private void escribir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribir4ActionPerformed
        txtMo.setVisible(true);
        txtMo.setText(escribir4.getText());
        escribir4.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_escribir4ActionPerformed

    private void escribir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribir3ActionPerformed
        txtM.setVisible(true);
        txtM.setText(escribir3.getText());
        escribir3.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_escribir3ActionPerformed

    private void txtMoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMoMouseClicked
        escribir4.setVisible(true);
        txtMo.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_txtMoMouseClicked

    private void txtMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMMouseClicked
        escribir3.setVisible(true);
        txtM.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_txtMMouseClicked

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
if(txtCelular.isSelected()){
    txtTablet.setEnabled(false);
    txtComputadora.setEnabled(false);
}
else{
    txtTablet.setEnabled(true);
    txtComputadora.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtTabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTabletActionPerformed
      if(txtTablet.isSelected()){
    txtCelular.setEnabled(false);
    txtComputadora.setEnabled(false);
}
else{
    txtCelular.setEnabled(true);
    txtComputadora.setEnabled(true);
}
    }//GEN-LAST:event_txtTabletActionPerformed

    private void txtComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComputadoraActionPerformed
if(txtComputadora.isSelected()){
    txtTablet.setEnabled(false);
    txtCelular.setEnabled(false);
}
else{
    txtTablet.setEnabled(true);
    txtCelular.setEnabled(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_txtComputadoraActionPerformed

    private void txtEncendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEncendidoActionPerformed
if(txtEncendido.isSelected()){
txtApagado.setEnabled(false);}
else{txtApagado.setEnabled(true);}// TODO add your handling code here:
    }//GEN-LAST:event_txtEncendidoActionPerformed

    private void txtApagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApagadoActionPerformed
if(txtApagado.isSelected()){
txtEncendido.setEnabled(false);}
else{txtEncendido.setEnabled(true);}        // TODO add your handling code here:
    }//GEN-LAST:event_txtApagadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel A1;
    private javax.swing.JLabel C;
    private javax.swing.JTextField D;
    private javax.swing.JLabel F;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JTextField G;
    private javax.swing.JLabel H;
    private javax.swing.JLabel JLFecha;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel NS;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Telefono;
    public javax.swing.JTextField escribir;
    private javax.swing.JTextField escribir2;
    private javax.swing.JTextField escribir3;
    private javax.swing.JTextField escribir4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JCheckBox txtApagado;
    private javax.swing.JCheckBox txtCelular;
    private javax.swing.JCheckBox txtComputadora;
    private javax.swing.JCheckBox txtEncendido;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtM;
    private javax.swing.JLabel txtMo;
    private javax.swing.JLabel txtN;
    private javax.swing.JLabel txtT;
    private javax.swing.JCheckBox txtTablet;
    // End of variables declaration//GEN-END:variables

     @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
if(pageIndex==0){
    Graphics2D graphics2d=(Graphics2D) graphics;
    graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
    printAll(graphics2d);
    return PAGE_EXISTS;
}
else{
    return NO_SUCH_PAGE;
}
    }
}
