/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.BarcodeException;
import net.sourceforge.barbecue.BarcodeFactory;
import net.sourceforge.barbecue.output.OutputException;

/**
 *
 * @author AlejandroSaenz
 */
public class PlantillaEtiqueta extends javax.swing.JPanel implements Printable {

     String nombreImagen="";
    BufferedImage imagen;
    public PlantillaEtiqueta() {
        initComponents();
    }
    public ImageIcon GenerarCodigo(String valor){
        try {
            Barcode codigo=null;
            
            codigo=BarcodeFactory.createCode128(valor);
            codigo.setDrawingText(false);
            codigo.setBarWidth(1);
            codigo.setBarHeight(45);
            imagen=new BufferedImage(300, 100, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g= (Graphics2D) imagen.getGraphics();
            codigo.draw(g, -11,20);
        } catch (BarcodeException | OutputException ex) {
            Logger.getLogger(AñadirProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon img=new ImageIcon(imagen);
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CIDE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbImagenCodigoE = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CIDE.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CIDE.setText("00000");
        add(CIDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("S");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbImagenCodigoE.setBackground(new java.awt.Color(255, 255, 255));
        lbImagenCodigoE.setOpaque(true);
        add(lbImagenCodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 69));
    }// </editor-fold>//GEN-END:initComponents

   @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
if(pageIndex==0){
    Graphics2D graphics2d=(Graphics2D) graphics;
    graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
    printAll(graphics2d);
    return PAGE_EXISTS;
}
else{
    return NO_SUCH_PAGE;
}
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel CIDE;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lbImagenCodigoE;
    // End of variables declaration//GEN-END:variables
}
