/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.BarcodeException;
import net.sourceforge.barbecue.BarcodeFactory;
import net.sourceforge.barbecue.output.OutputException;

/**
 *
 * @author AlejandroSaenz
 */
public class PlantillaCBL extends javax.swing.JPanel  implements Printable{

    String nombreImagen="";
    BufferedImage imagen;
    public PlantillaCBL() {
        initComponents();
       Id.setVisible(false);
C.setVisible(true);
txtId.setVisible(false);
    }
private ImageIcon GenerarCodigo(String valor){
        try {
            Barcode codigo=null;
            
            codigo=BarcodeFactory.createCode128(valor);
            codigo.setDrawingText(false);
            codigo.setBarWidth(1);
            codigo.setBarHeight(45);
            imagen=new BufferedImage(300, 100, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g= (Graphics2D) imagen.getGraphics();
            codigo.draw(g, 5,20);
        } catch (BarcodeException | OutputException ex) {
            Logger.getLogger(AñadirProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon img=new ImageIcon(imagen);
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        C = new javax.swing.JTextField();
        lbImagenCodigo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Id.setText("P");
        add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtId.setText("1");
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
        });
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CKeyTyped(evt);
            }
        });
        add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 70, -1));

        lbImagenCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lbImagenCodigo.setOpaque(true);
        add(lbImagenCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 69));
    }// </editor-fold>//GEN-END:initComponents

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
Id.setVisible(true);
 lbImagenCodigo.setIcon(GenerarCodigo(C.getText()));
 txtId.setText(C.getText());
C.setVisible(false);
txtId.setVisible(true);
    }//GEN-LAST:event_CActionPerformed

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
 Id.setVisible(false);
C.setVisible(true);
txtId.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMouseClicked

    private void CKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CKeyTyped
char car = evt.getKeyChar();
    if (car!='.'&&car!='0'&&car!='1'&&car!='2'&&car!='3'&&car!='4'&&car!='5'&&car!='6'&&car!='7'&&car!='8'&&car!='9')
      evt.consume();          // TODO add your handling code here:
    }//GEN-LAST:event_CKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel lbImagenCodigo;
    private javax.swing.JLabel txtId;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
if(pageIndex==0){
    Graphics2D graphics2d=(Graphics2D) graphics;
    graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
    printAll(graphics2d);
    return PAGE_EXISTS;
}
else{
    return NO_SUCH_PAGE;
}
    }
}
