/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Metodos.Metodos;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.BarcodeException;
import net.sourceforge.barbecue.BarcodeFactory;
import net.sourceforge.barbecue.output.OutputException;

/**
 *
 * @author AlejandroSaenz
 */
public class PlantillaCB extends javax.swing.JPanel  implements Printable{

    
     String nombreImagen="";
    BufferedImage imagen;
    public PlantillaCB() {
        initComponents();
         txtId.setText(""+ConsultarId());
        lbImagenCodigo.setIcon(GenerarCodigo(txtId.getText()));
    }
    private int ConsultarId(){
    Metodos M=new Metodos();
    int X=M.ConsultarIdProductos();
    
   return X;}
    private ImageIcon GenerarCodigo(String valor){
        try {
            Barcode codigo=null;
            
            codigo=BarcodeFactory.createCode128(valor);
            codigo.setDrawingText(false);
            codigo.setBarWidth(1);
            codigo.setBarHeight(45);
            imagen=new BufferedImage(300, 100, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g= (Graphics2D) imagen.getGraphics();
            codigo.draw(g, 5,20);
        } catch (BarcodeException | OutputException ex) {
            Logger.getLogger(AñadirProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon img=new ImageIcon(imagen);
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        lbImagenCodigo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("P");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtId.setText("1");
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lbImagenCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lbImagenCodigo.setOpaque(true);
        add(lbImagenCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 69));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImagenCodigo;
    private javax.swing.JLabel txtId;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
if(pageIndex==0){
    Graphics2D graphics2d=(Graphics2D) graphics;
    graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
    printAll(graphics2d);
    return PAGE_EXISTS;
}
else{
    return NO_SUCH_PAGE;
}
    }
}
