/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DProductos;
import Datos.DVentas;
import Metodos.Metodos;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.MediaSizeName;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlejandroSaenz
 */
public class Ventas extends javax.swing.JFrame {

     DefaultTableModel modelo;
     public int renglon;
    public Ventas() {
     
        initComponents();
       renglon=0;
         txtD.setVisible(false);
      txtP.setVisible(false);
      btnA.setVisible(false);
      t.setVisible(false);
p.setVisible(false);
        T.requestFocus();
        
        Tabla.setBackground(Color.white);
        
        txtE.requestFocus();
        TablaPrecios.setVisible(false);
        setLocationRelativeTo(null);
    }
public void Total(){
    int contar=Tabla.getRowCount();
    float suma=0;
    for (int i=0; i < contar;i++){
        suma=suma+Float.parseFloat(Tabla.getValueAt(i, 1).toString());
       T.setText(""+suma);
    }
     
    
    
}    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cerrar = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        plantillaVentas1 = new Presentacion.PlantillaVentas();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Publico = new javax.swing.JTextField();
        T = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fin = new javax.swing.JLabel();
        mas = new javax.swing.JLabel();
        txtP = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        btnA = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPrecios = new javax.swing.JTable();
        txtV = new javax.swing.JComboBox<>();
        lbregresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(242, 241, 246));

        Cerrar.setBackground(new java.awt.Color(204, 204, 204));
        Cerrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(102, 102, 102));
        Cerrar.setText("X");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantillaVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantillaVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Descripcion", "Precio"
            }
        ));
        Tabla.setAutoscrolls(false);
        Tabla.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        Tabla.setGridColor(new java.awt.Color(0, 0, 0));
        Tabla.setOpaque(false);
        jScrollPane2.setViewportView(Tabla);

        Publico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicoActionPerformed(evt);
            }
        });

        T.setText("0.0");

        jLabel1.setText("Total");

        Fin.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Fin.setText("Finalizar");
        Fin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        Fin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FinMouseExited(evt);
            }
        });

        mas.setText("+");
        mas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masMouseExited(evt);
            }
        });

        btnA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnA.setText("Agregar");
        btnA.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAMouseExited(evt);
            }
        });

        t.setText("Descripcion");

        p.setText("Precio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(615, 615, 615)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(T))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Publico, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mas)
                        .addGap(50, 50, 50)
                        .addComponent(t)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(p)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnA)))
                .addGap(293, 293, 293))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Publico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mas)
                    .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t)
                    .addComponent(p))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T)
                    .addComponent(jLabel1))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(242, 241, 246));

        txtE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEActionPerformed(evt);
            }
        });
        txtE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEKeyReleased(evt);
            }
        });

        TablaPrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaPrecios);

        txtV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Descripcion" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Precios", jPanel3);

        lbregresar.setBackground(new java.awt.Color(0, 0, 255));
        lbregresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbregresar.setForeground(new java.awt.Color(0, 51, 255));
        lbregresar.setText("< Regresar");
        lbregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbregresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbregresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbregresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Cerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbregresar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbregresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseClicked

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        Cerrar.setOpaque(true);
        Cerrar.setBackground(Color.red);
        Cerrar.setForeground(Color.white);
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        Cerrar.setOpaque(false);
        Cerrar.setBackground(Color.lightGray);
        Cerrar.setForeground(Color.black);// TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseExited

    private void txtEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEActionPerformed
     Metodos Met=new Metodos();
     Met.ConsultarPrecios(Integer.parseInt(txtE.getText()),TablaPrecios);
     TablaPrecios.setVisible(true);
     txtE.setText("");
    }//GEN-LAST:event_txtEActionPerformed

    private void lbregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbregresarMouseClicked
      Principal P=new Principal();
      P.setVisible(true);
      dispose();
    }//GEN-LAST:event_lbregresarMouseClicked

    private void lbregresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbregresarMouseEntered
    lbregresar.setOpaque(true);
lbregresar.setBackground(Color.lightGray);
lbregresar.setForeground(Color.black);
    }//GEN-LAST:event_lbregresarMouseEntered

    private void lbregresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbregresarMouseExited
 lbregresar.setOpaque(false);
lbregresar.setBackground(Color.lightGray);
lbregresar.setForeground(Color.blue);        // TODO add your handling code here:
    }//GEN-LAST:event_lbregresarMouseExited

    private void txtEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEKeyReleased
if(!txtV.getSelectedItem().toString().equals("Id")){TablaPrecios.setVisible(true);
        Metodos articulo = new Metodos();
        articulo.BuscarArticulo(TablaPrecios, txtE.getText(), txtV.getSelectedItem().toString());
}
    }//GEN-LAST:event_txtEKeyReleased

    private void PublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicoActionPerformed


        Metodos M=new Metodos();
      DProductos R=new DProductos();
      R.setId(Integer.parseInt(Publico.getText()));
      M.BuscarProducto(R);
       Tabla.setValueAt(R.getDescripcion(), renglon, 0);
        Tabla.setValueAt(R.getPrecio(), renglon, 1);
         renglon++;
      
        plantillaVentas1.Tabla.setValueAt(R.getDescripcion(), plantillaVentas1.renglon, 0);
        plantillaVentas1.Tabla.setValueAt(R.getPrecio(), plantillaVentas1.renglon, 1);
       plantillaVentas1.renglon++;
     try{  
    Total();
plantillaVentas1.Total();}
     catch(Exception e){System.out.println();}
Publico.setText(""); 
 
     // TODO add your handling code here:
    }//GEN-LAST:event_PublicoActionPerformed

    private void FinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinMouseEntered
Fin.setOpaque(true);      
Fin.setBackground(Color.lightGray);
Fin.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_FinMouseEntered

    private void FinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinMouseExited
Fin.setOpaque(false);      
Fin.setBackground(Color.white);
Fin.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_FinMouseExited

    private void FinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinMouseClicked
plantillaVentas1.T.setText(T.getText());
        for(int i=0; i<Tabla.getRowCount();i++){
                DVentas vtas= new DVentas();
                if(Tabla.getValueAt(i,0)!=null){
                    vtas.setFolio(Integer.parseInt(plantillaVentas1.txtFolio.getText()));
                   
                    vtas.setDescripcion(Tabla.getValueAt(i,0).toString());
                    vtas.setPrecio(Float.parseFloat(Tabla.getValueAt(i,1).toString()));
                    Metodos M=new Metodos();
                    M.GuardarVentas(vtas);
                    
                }
            }
            plantillaVentas1.txtFolio.setText(""+plantillaVentas1.ConsultarFolio());
           JOptionPane.showMessageDialog(null, "Venta registrada");
        int n=JOptionPane.showConfirmDialog(null, "¿Imprimir Ticket?: ");
        if(n==0){
            PrinterJob job=PrinterJob.getPrinterJob();
       
       job.setPrintable(plantillaVentas1);
       if(job.printDialog()){
           try {
              PrintRequestAttributeSet aset = new HashPrintRequestAttributeSet();

                aset.add(OrientationRequested.PORTRAIT);
                aset.add(MediaSizeName.ISO_C5);
                   
                job.print(aset);
           } catch (PrinterException ex) {
               System.out.println("catch");           }
       }
       else{
           JOptionPane.showMessageDialog(null, "La impresion se Canceló");}
                 Ventas v=new Ventas();
            v.setVisible(true);
            dispose();
           
        }       
    }//GEN-LAST:event_FinMouseClicked

    private void masMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseEntered
mas.setOpaque(true);
mas.setBackground(Color.lightGray);
// TODO add your handling code here:
    }//GEN-LAST:event_masMouseEntered

    private void masMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseExited
mas.setOpaque(false);
mas.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_masMouseExited

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
      
    }//GEN-LAST:event_jPanel2MouseClicked

    private void masMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseClicked
txtD.setVisible(true);
      txtP.setVisible(true);
      btnA.setVisible(true);
t.setVisible(true);
p.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_masMouseClicked

    private void btnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseClicked
      Tabla.setValueAt(txtD.getText(), renglon, 0);
      Tabla.setValueAt(txtP.getText(), renglon, 1);
      renglon++;
       plantillaVentas1.Tabla.setValueAt(txtD.getText(), plantillaVentas1.renglon, 0);
      plantillaVentas1.Tabla.setValueAt(txtP.getText(), plantillaVentas1.renglon, 1);
      plantillaVentas1.renglon++;
      try{Total();}
      catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_btnAMouseClicked

    private void btnAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAMouseEntered

    private void btnAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel Fin;
    private javax.swing.JTextField Publico;
    private javax.swing.JLabel T;
    private javax.swing.JTable Tabla;
    private javax.swing.JTable TablaPrecios;
    private javax.swing.JLabel btnA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbregresar;
    private javax.swing.JLabel mas;
    private javax.swing.JLabel p;
    private Presentacion.PlantillaVentas plantillaVentas1;
    private javax.swing.JLabel t;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtP;
    private javax.swing.JComboBox<String> txtV;
    // End of variables declaration//GEN-END:variables
}
